/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Andyman' at '4/4/17 12:25 PM' with Gradle 2.14.1
 *
 * @author Andyman, @date 4/4/17 12:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
